name: Python CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tu as un fichier requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --show-source --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/ -v  # Remplace "tests/" par ton dossier de tests
